<a href="https://colab.research.google.com/github/AnIsAsPe/Fundamentos-tecnicos-y-aplicaciones-ML/blob/main/2_1_Algoritmo_Matrimonio_Estable_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importar bibliotecas

In [1]:
import numpy as np

#Funciones

### pref_mujeres_h1_sobre_h()

In [2]:
 
def pref_mujeres_h1_sobre_h(preferencia, m, h, h1): 
  '''Esta función prueba si la mujer 'm' prefiere al hombre 'h1'
     sobre el hombre 'h' '''
  N = preferencia.shape[1]

  for i in range(N): 
          
      # Si h1 está antes de h en la lista de m,  
      # entonces la mujer se queda con el hombre h1
      if (preferencia[m][i] == h1): 
          return True
  
      # En caso contrario m  se queda con h
      if (preferencia[m][i] == h): 
          return False

### stableMarriage()

In [3]:
#def stableMarriage(preferencia, posicion1='hombre', posicion2='mujer'): 
def stableMarriage(preferencia): 
  '''Regresa una matriz con las parejas formadas en cada renglón.
     preferencias: Matriz que guarda las preferencias de dos grupos de actores a 
     ser emparejados (por ejemplo: hombres y mujeres) 
     Las preferencias de cada uno de los hombres se encuentran en los
     renglones del 0 al N-1.  
     Las preferencias de cada una de las mujeres están desde el 
     el renglón N al 2N-1
     referencia: https://www.geeksforgeeks.org/stable-marriage-problem/ '''
     
  N = preferencia.shape[1]

  # La lista muj_pareja guarda la pareja de las mujeres  
  # el valor muj_pareja[i] es el valor de la pareja asignada a la mujer N+i
  # cuando el valore es -1 indica que la mujer está libre
  muj_pareja = [-1 for i in range(N)]  
  
  # la lista h_comprometido va a guardar el estatus de cada hombre, el
  # valor de h_comprometiod[i] es verdadero cuando está comprometido y falso
  # cuando está libre. 
  h_comprometido = [False for i in range(N)] 
  
  libres = N 
  
  #Mientras existan hombres libres
  while (libres > 0):  
    # Escoje cualquier hombre libre
    h = 0
    while (h < N): 
        # si el hombre h está no está comprometido, se rompe el ciclo while
        if (h_comprometido[h] == False):         
          break
        # de otra manera se prueba con el que sigue hasta encontrar uno libre 
        h += 1      
  
    # h es entonces un hombre libre y se buscara una mujer de acuerdo con 
    # sus preferencias 
    i = 0
    while i < N and h_comprometido[h] == False: 
      m = preferencia[h][i] 
  
      # Si la primera mujer de sus preferencias m está libre,  
      # m y h se comprometen (no se casan) 
      if (muj_pareja[m - N] == -1): 
          muj_pareja[m - N] = h 
          h_comprometido[h] = True
          libres -= 1  #ser resta uno a los hombres libres

      else:
                  
          # Si la mujer no está libre, se reviza con qué hombre esta comprometida
          h1 = muj_pareja[m - N] 
  
          # Se revisa si la mujer prefiere a su compormetido (h1) sobre  h. 
          if (pref_mujeres_h1_sobre_h(preferencia, m, h, h1) == False): 
              muj_pareja[m - N] = h 
              h_comprometido[h] = True
              h_comprometido[h1] = False
      i += 1 
  
  hombres = np.array(muj_pareja)
  mujeres = np.arange(N, 2*N)
  parejas =np.column_stack((mujeres, hombres))

  return parejas

# Ejemplo 1 Parejas estables entre hombres y mujeres de acuerdo a sus preferencias

In [8]:
#Construcción de una matriz de preferencias
pref = {}  #inicia dic para guardar las preferencias ordenadas de hombres y mujeres

#las preferencias de los hombres se guardaran de la clave 0 a la clave 4
for i in range(0, 5): 
  pref[i] = np.random.choice(range(5, 10), 5, replace=False)

#las preferencias de las mujeres se guardaran de la clave 5 a la clave 9   
for i in range(5,10):
  pref[i] = np.random.choice( range(0, 5), 5, replace=False) #genera preferenciaencias de las mujeres
  
pref

{0: array([6, 8, 7, 5, 9]),
 1: array([7, 9, 6, 5, 8]),
 2: array([7, 8, 5, 6, 9]),
 3: array([7, 6, 9, 5, 8]),
 4: array([7, 9, 5, 6, 8]),
 5: array([4, 3, 0, 2, 1]),
 6: array([4, 1, 3, 0, 2]),
 7: array([2, 4, 3, 0, 1]),
 8: array([1, 0, 4, 2, 3]),
 9: array([3, 0, 1, 2, 4])}

In [11]:
preferencia = np.stack(list(pref.values()), axis=0)
preferencia

array([[6, 8, 7, 5, 9],
       [7, 9, 6, 5, 8],
       [7, 8, 5, 6, 9],
       [7, 6, 9, 5, 8],
       [7, 9, 5, 6, 8],
       [4, 3, 0, 2, 1],
       [4, 1, 3, 0, 2],
       [2, 4, 3, 0, 1],
       [1, 0, 4, 2, 3],
       [3, 0, 1, 2, 4]])

In [12]:
parejas = stableMarriage(preferencia)
parejas

array([[5, 4],
       [6, 3],
       [7, 2],
       [8, 0],
       [9, 1]])

**el algoritmo no es simétrico**

In [13]:
parejas2 = stableMarriage(np.concatenate((preferencia[6:,],preferencia[0:5,]), axis=0))
parejas2

array([[5, 4],
       [6, 2],
       [7, 1],
       [8, 3],
       [9, 0]])

In [14]:
import pandas as pd
pref = pd.DataFrame(preferencia, columns = ['P_'+str(i) for i in range(1,6)])
pref

P_1  P_2  P_3  P_4  P_5
0    6    8    7    5    9
1    7    9    6    5    8
2    7    8    5    6    9
3    7    6    9    5    8
4    7    9    5    6    8
5    4    3    0    2    1
6    4    1    3    0    2
7    2    4    3    0    1
8    1    0    4    2    3
9    3    0    1    2    4

In [ ]:
pref.min()

# Ejemplo 2 Recomendacion emparejamiento candidatos-empleos

Conjunto de datos generado a partir del [github](https://github.com/AmarSaini/PrivateJobMatch) [2]

In [15]:
candidatos = np.genfromtxt('https://raw.githubusercontent.com/AnIsAsPe/Fundamentos-tecnicos-y-aplicaciones-ML/main/Datos/dense_candidate_prefs.csv',
                           delimiter=',')
candidatos.shape

(100, 100)

In [16]:
candidatos.min(), candidatos.max()  #nueva linea

(1.0, 100.0)

In [17]:
candidatos = candidatos - 1   #nueva línea
candidatos = candidatos + 100  #nueva linea
candidatos.min(), candidatos.max()  #nueva linea

(100.0, 199.0)

In [18]:
empleadores = np.genfromtxt('https://raw.githubusercontent.com/AnIsAsPe/Fundamentos-tecnicos-y-aplicaciones-ML/main/Datos/dense_employer_prefs.csv',
                            delimiter=',')
empleadores.shape

(100, 100)

In [19]:
empleadores.min(), empleadores.max()  #nueva linea

(1.0, 100.0)

In [20]:
empleadores = empleadores - 1   #nueva línea
empleadores.min(), empleadores.max()  #nueva linea

(0.0, 99.0)

In [21]:
matriz_pref = np.concatenate((candidatos,empleadores), axis=0)
matriz_pref = matriz_pref.astype('int64')
matriz_pref.shape

(200, 100)

In [22]:
candidatos_empleadores = stableMarriage(matriz_pref)
candidatos_empleadores.shape

(100, 2)

In [23]:
candidatos_empleadores

array([[100,  20],
       [101,  98],
       [102,  32],
       [103,  59],
       [104,  31],
       [105,  84],
       [106,  27],
       [107,  40],
       [108,  36],
       [109,   0],
       [110,  26],
       [111,  97],
       [112,  95],
       [113,  92],
       [114,  85],
       [115,  48],
       [116,  34],
       [117,  38],
       [118,  51],
       [119,  37],
       [120,   5],
       [121,  52],
       [122,  90],
       [123,  81],
       [124,  66],
       [125,  78],
       [126,  22],
       [127,  64],
       [128,  50],
       [129,  68],
       [130,  86],
       [131,  41],
       [132,  70],
       [133,  89],
       [134,  56],
       [135,  10],
       [136,  74],
       [137,  23],
       [138,  54],
       [139,  67],
       [140,  77],
       [141,  13],
       [142,   3],
       [143,  63],
       [144,  15],
       [145,   6],
       [146,  61],
       [147,  12],
       [148,  29],
       [149,  82],
       [150,  42],
       [151,  16],
       [152,

# Referencias:

1. Stable Marriage Problem [Internet]. GeeksforGeeks. 2013 [citado 13 de diciembre de 2020]. Disponible en: https://www.geeksforgeeks.org/stable-marriage-problem/


2. Saini A, Rusu F, Johnston A. PrivateJobMatch: a privacy-oriented deferred multi-match recommender system for stable employment. En: Proceedings of the 13th ACM Conference on Recommender Systems [Internet]. Copenhagen Denmark: ACM; 2019 [citado 24 de noviembre de 2020]. p. 87-95. Disponible en: https://dl.acm.org/doi/10.1145/3298689.3346983
