<a href="https://colab.research.google.com/github/AnIsAsPe/Fundamentos-tecnicos-y-aplicaciones-ML/blob/main/02_Vectores_y_Matrices_con_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

La librería Numpy nos permite usar funciones matemáticas de vectores y matrices. Está implementada en C y Fortran, por lo que este tipo de operaciones tiene un rendimiento muy bueno. A diferencia de las listas (una matriz, podría ser una lista anidada) para las que su comportamiento es dinámico, los arreglos de numpy son estáticos y homogeneos, lo que los vuelve muy eficientes en el uso de la memoria.

In [ ]:
import numpy as np  # importar la librería

### np.array()

#### Crear un vector (1-D array)

In [ ]:
lista = [1,2,3]
vector = np.array(lista)
vector

array([1, 2, 3])

#### Crear una Matriz (2-D array)

In [ ]:

M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [ ]:
A = np.random.rand(4,3)
A

array([[0.49883116, 0.96956039, 0.58705275],
       [0.28760983, 0.74960389, 0.95493582],
       [0.24127957, 0.37334927, 0.19554479],
       [0.50980316, 0.49226345, 0.89323021]])

#### Acceder a los elementos de un vector o matriz

In [ ]:
A[1,:] #fila 1

array([0.        , 0.74960389, 1.90987164])

In [ ]:
A[:,1] # columna 1

array([0.96956039, 0.74960389, 0.37334927, 0.49226345])

In [ ]:
A[1,1]

0.7496038909086992

In [ ]:
A[1:,:]

array([[0.28760983, 0.74960389, 0.95493582],
       [0.24127957, 0.37334927, 0.19554479],
       [0.50980316, 0.49226345, 0.89323021]])

### np.arange()

parecido a range()

In [ ]:
for i in range(0,10,2):
  print(i)

e = range(0,10,2)
e

0
2
4
6
8


range(0, 10, 2)

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### np.linspace()



In [ ]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### np.random()


In [ ]:
B = np.random.rand(3,3)
B

array([[0.65328321, 0.41999096, 0.12585521],
       [0.56667659, 0.46660402, 0.40594538],
       [0.40698745, 0.27461329, 0.85892015]])

In [ ]:
v = np.random.randint(1,200,20)
v

array([ 14, 129, 130, 116, 173,  59, 169, 131, 128, 139, 126,  88, 114,
        62,  35,   4, 191,  96, 131,  19])

### método reshape()



In [ ]:
C = v.reshape(4,5)
C

array([[ 14, 129, 130, 116, 173],
       [ 59, 169, 131, 128, 139],
       [126,  88, 114,  62,  35],
       [  4, 191,  96, 131,  19]])

### atributo shape()

In [ ]:
C.shape

(4, 5)

In [ ]:
C.reshape(2,-1)

array([[ 14, 129, 130, 116, 173,  59, 169, 131, 128, 139],
       [126,  88, 114,  62,  35,   4, 191,  96, 131,  19]])

### min()  max()  sum() mean() 



In [ ]:
C.max()

191

In [ ]:
C.min()

4

In [ ]:
C.sum()

2054

In [ ]:
C.mean()

102.7

### operaciones con vectories y matrices

In [ ]:
vector

array([0, 1, 2])

In [ ]:
2 * vector

array([0, 2, 4])

In [ ]:
A = vector*A
A

array([[0.        , 0.96956039, 1.1741055 ],
       [0.        , 0.74960389, 1.90987164],
       [0.        , 0.37334927, 0.39108958],
       [0.        , 0.49226345, 1.78646042]])

In [ ]:
A + 5

array([[5.        , 5.96956039, 6.1741055 ],
       [5.        , 5.74960389, 6.90987164],
       [5.        , 5.37334927, 5.39108958],
       [5.        , 5.49226345, 6.78646042]])