<a href="https://colab.research.google.com/github/AnIsAsPe/Fundamentos-tecnicos-y-aplicaciones-ML/blob/main/2_1_Algoritmo_Matrimonio_Estable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Importar bibliotecas

In [28]:
import numpy as np

#Funciones

### pref_mujeres_h1_sobre_h()

In [29]:
 
def pref_mujeres_h1_sobre_h(preferencia, m, h, h1): 
  '''Esta función prueba si la mujer 'm' prefiere al hombre 'h1'
     sobre el hombre 'h' '''
  N = preferencia.shape[1]

  for i in range(N): 
          
      # Si h1 está antes de h en la lista de m,  
      # entonces la mujer se queda con el hombre h1
      if (preferencia[m][i] == h1): 
          return True
  
      # En caso contrario m  se queda con h
      if (preferencia[m][i] == h): 
          return False

### stableMarriage()

In [30]:
def stableMarriage(preferencia, posicion1='hombre', posicion2='mujer'): 
  '''Regresa una matriz con las parejas formadas en cada renglón.
     preferencias: Matriz que guarda las preferencias de dos grupos de actores a 
     ser emparejados (por ejemplo: hombres y mujeres) 
     Las preferencias de cada uno de los hombres se encuentran en los
     renglones del 0 al N-1.  
     Las preferencias de cada una de las mujeres están desde el 
     el renglón N al 2N-1
     referencia: https://www.geeksforgeeks.org/stable-marriage-problem/ '''
     
  N = preferencia.shape[1]

  # La lista muj_pareja guarda la pareja de las mujeres  
  # el valor muj_pareja[i] es el valor de la pareja asignada a la mujer N+i
  # cuando el valore es -1 indica que la mujer está libre
  muj_pareja = [-1 for i in range(N)]  
  
  # la lista h_comprometido va a guardar el estatus de cada hombre, el
  # valor de h_comprometiod[i] es verdadero cuando está comprometido y falso
  # cuando está libre. 
  h_comprometido = [False for i in range(N)] 
  
  libres = N 
  
  #Mientras existan hombres libres
  while (libres > 0):  
    # Escoje cualquier hombre libre
    h = 0
    while (h < N): 
        # si el hombre h está no está comprometido, se rompe el ciclo while
        if (h_comprometido[h] == False):         
          break
        # de otra manera se prueba con el que sigue hasta encontrar uno libre 
        h += 1      
  
    # h es entonces un hombre libre y se buscara una mujer de acuerdo con 
    # sus preferencias 
    i = 0
    while i < N and h_comprometido[h] == False: 
      m = preferencia[h][i] 
  
      # Si la primera mujer de sus preferencias m está libre,  
      # m y h se comprometen (no se casan) 
      if (muj_pareja[m - N] == -1): 
          muj_pareja[m - N] = h 
          h_comprometido[h] = True
          libres -= 1  #ser resta uno a los hombres libres

      else:
                  
          # Si la mujer no está libre, se reviza con qué hombre esta comprometida
          h1 = muj_pareja[m - N] 
  
          # Se revisa si la mujer prefiere a su compormetido (h1) sobre  h. 
          if (pref_mujeres_h1_sobre_h(preferencia, m, h, h1) == False): 
              muj_pareja[m - N] = h 
              h_comprometido[h] = True
              h_comprometido[h1] = False
      i += 1 
  
  hombres = np.array(muj_pareja)
  mujeres = np.arange(N, 2*N)
  parejas =np.column_stack((mujeres, hombres))

  return parejas

# Ejemplo 1 Parejas estables entre hombres y mujeres de acuerdo a sus preferencias

In [31]:
#Construcción de una matriz de preferencias
pref = {}  #inicia dic para guardar las preferencias ordenadas de hombres y mujeres

#las preferencias de los hombres se guardaran de la clave 0 a la clave 4
for i in range(0, 5): 
  pref[i] = np.random.choice(range(5,10), 5, replace=False)

#las preferencias de las mujeres se guardaran de la clave 5 a la clave 9   
for i in range(5,10):
  pref[i] = np.random.choice( range(0, 5), 5, replace=False) #genera preferenciaencias de las mujeres
  
pref

{0: array([6, 5, 8, 7, 9]),
 1: array([6, 5, 7, 8, 9]),
 2: array([8, 9, 7, 5, 6]),
 3: array([5, 9, 6, 8, 7]),
 4: array([6, 8, 7, 5, 9]),
 5: array([1, 3, 4, 0, 2]),
 6: array([0, 3, 1, 2, 4]),
 7: array([2, 4, 3, 0, 1]),
 8: array([0, 1, 3, 4, 2]),
 9: array([2, 0, 4, 3, 1])}

In [32]:
preferencia = np.stack(list(pref.values()), axis=0)
print(preferencia.shape)
preferencia

(10, 5)


array([[6, 5, 8, 7, 9],
       [6, 5, 7, 8, 9],
       [8, 9, 7, 5, 6],
       [5, 9, 6, 8, 7],
       [6, 8, 7, 5, 9],
       [1, 3, 4, 0, 2],
       [0, 3, 1, 2, 4],
       [2, 4, 3, 0, 1],
       [0, 1, 3, 4, 2],
       [2, 0, 4, 3, 1]])

In [33]:
parejas = stableMarriage(preferencia, 'hombre', 'mujer')
parejas

array([[5, 1],
       [6, 0],
       [7, 4],
       [8, 3],
       [9, 2]])

# Ejemplo 2 Recomendacion emparejamiento candidatos-empleos

Conjunto de datos generado a partir del [github](https://github.com/AmarSaini/PrivateJobMatch) [2]

In [34]:
candidatos = np.genfromtxt('https://raw.githubusercontent.com/AnIsAsPe/Fundamentos-tecnicos-y-aplicaciones-ML/main/Datos/dense_candidate_prefs.csv',
                           delimiter=',')
candidatos.shape

(100, 100)

In [36]:
empleadores = np.genfromtxt('https://raw.githubusercontent.com/AnIsAsPe/Fundamentos-tecnicos-y-aplicaciones-ML/main/Datos/dense_employer_prefs.csv',
                            delimiter=',')
empleadores.shape

(100, 100)

In [37]:
matriz_pref = np.concatenate((candidatos,empleadores), axis=0)
matriz_pref = matriz_pref.astype('int64')
matriz_pref.shape

(200, 100)

In [38]:
candidatos_empleadores = stableMarriage(matriz_pref, 'candidato', 'empleador')
candidatos_empleadores.shape

(100, 2)

In [39]:
candidatos_empleadores

array([[100,  33],
       [101,  54],
       [102,  22],
       [103,   4],
       [104,   3],
       [105,  52],
       [106,  75],
       [107,  26],
       [108,  67],
       [109,  36],
       [110,  71],
       [111,  28],
       [112,  89],
       [113,  95],
       [114,   8],
       [115,  66],
       [116,  63],
       [117,  85],
       [118,  56],
       [119,  43],
       [120,  55],
       [121,  59],
       [122,   2],
       [123,  90],
       [124,  81],
       [125,  72],
       [126,  11],
       [127,  70],
       [128,  19],
       [129,  74],
       [130,  65],
       [131,  45],
       [132,  41],
       [133,  61],
       [134,  37],
       [135,   1],
       [136,  88],
       [137,  34],
       [138,  78],
       [139,  80],
       [140,  27],
       [141,  10],
       [142,  13],
       [143,   7],
       [144,  93],
       [145,  40],
       [146,  92],
       [147,  47],
       [148,  76],
       [149,  42],
       [150,  77],
       [151,  64],
       [152,

# Referencias:

1. Stable Marriage Problem [Internet]. GeeksforGeeks. 2013 [citado 13 de diciembre de 2020]. Disponible en: https://www.geeksforgeeks.org/stable-marriage-problem/


2. Saini A, Rusu F, Johnston A. PrivateJobMatch: a privacy-oriented deferred multi-match recommender system for stable employment. En: Proceedings of the 13th ACM Conference on Recommender Systems [Internet]. Copenhagen Denmark: ACM; 2019 [citado 24 de noviembre de 2020]. p. 87-95. Disponible en: https://dl.acm.org/doi/10.1145/3298689.3346983
